import type { Metadata } from "next";
import { Nunito, Luckiest_Guy, Courier_Prime } from "next/font/google";
import "./globals.css";

const nunuto = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const luckiestGuy = Luckiest_Guy({
  variable: "--font-luckiest-guy",
  subsets: ["latin"],
  weight: "400",
});

const courierPrime = Courier_Prime({
  variable: "--font-courier-prime",
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "Artem Zabava",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${nunuto.variable} ${luckiestGuy.variable} ${courierPrime.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
